### ISSUE TITLE
Puzzle 6 - shape annotation for x

### ISSUE THREAD

**Issue by lucaslingle** [srush/Triton-Puzzles#11]
For "Puzzle 6: Fused Outer Multiplication - Backwards", x appears to have the same meaning as in the previous problem. 
However, it is annotated as having shape [90, 100] instead of [100]. Is this a typo?

**Comment by srush** [comment]
Ah, sorry there is a bug in the math there. the Shape 90, 100 is correct, but it should be x_{j, i} in the math.

**Comment by lucaslingle** [comment]
I figured out, thanks!
